### ISSUE TITLE
The citation file cannot be parsed

### ISSUE THREAD

**Issue by EgbertRijke** [UniMath/agda-unimath#517]
When clicking the "cite this repository" button in the about panel on the main page of our repository, I get the message

> Your CITATION.cff file cannot be parsed. Make sure the formatting is correct.

**Comment by fredrik-bakke** [comment]
This is due to the fact that `.cff` is a `.yaml` based format, and should not be formatted as a BibTeX reference.

Here's a sample corrected `CITATION.cff` file:
```yaml
cff-version: 1.2.0
message: "If you use this software, please cite it as below."
authors:
  - family-names: "Rijke"
    given-names: "Egbert"
  - family-names: "Bonnevier"
    given-names: "Elisabeth"
  - family-names: "Prieto-Cubides"
    given-names: "Jonathan"
  - name: "others"
title: "Univalent mathematics in Agda"
abstract: "The agda-unimath library is a community formalisation project for univalent mathematics in Agda. Our goal is to formalize an extensive curriculum of mathematics from the univalent point of view. Furthermore, we think libraries of formalized mathematics have the potential to be useful, and informative resources for mathematicians. Our library is designed to work towards this goal, and we welcome contributions to the library about any topic in mathematics."
repository-code: "https://github.com/UniMath/agda-unimath/"
url: "https://unimath.github.io/agda-unimath/"
keywords:
  - type-theory
  - homotopy-type-theory
  - univalent-foundations
```

GitHub can then compile this information to generate a BibTeX reference.

For a reference on the file format see: https://citation-file-format.github.io/
